import { BillMeta, Node, ExplainRequest, ExplainResponse } from './types';

// Mock data based on plan
const mockBills: BillMeta[] = [
  {
    id: "approp-2024",
    title: "FY2024 Appropriations Act",
    description: "A comprehensive budget act detailing federal spending across major departments for the 2024 fiscal year."
  },
  {
    id: "edu-tech-2023",
    title: "Education Technology Advancement Act",
    description: "Focuses on modernizing school infrastructure with new technology grants and phasing out outdated programs."
  },
  {
    id: "eo-ai-safety",
    title: "Executive Order on Safe AI",
    description: "Establishing new standards for AI safety and security, protecting privacy, and advancing equity."
  }
];

const mockHierarchy: Record<string, Node> = {
  "approp-2024": {
    name: "FY2024 Appropriations Act",
    amount: 1500000000,
    type: "neutral",
    summary: "Total discretionary spending for FY2024.",
    affects: "All federal agencies",
    children: [
      {
        name: "Department of Defense",
        amount: 850000000,
        type: "increase",
        summary: "Increased funding for modernization and readiness.",
        affects: "Military personnel and defense contractors",
        children: []
      },
      {
        name: "Department of Education",
        amount: 80000000,
        type: "cut",
        summary: "Reduced funding for legacy administrative programs.",
        affects: "Federal education administrators",
        children: []
      },
      {
        name: "Clean Energy Initiative",
        amount: 120000000,
        type: "new",
        summary: "New grants for renewable energy research.",
        affects: "Energy researchers and green tech companies",
        children: []
      }
    ]
  },
  "edu-tech-2023": {
    name: "Education Technology Advancement Act",
    amount: 500000000,
    type: "increase",
    summary: "Funding for nationwide K-12 technology integration.",
    affects: "Students and teachers",
    children: [
      {
        name: "Rural Broadband Grants",
        amount: 250000000,
        type: "new",
        summary: "Grants to build broadband infrastructure in rural school districts.",
        affects: "Rural communities",
        children: []
      },
      {
        name: "Legacy Textbook Subsidies",
        amount: 0,
        type: "repeal",
        summary: "Eliminates subsidies for physical textbooks.",
        affects: "Textbook publishers",
        children: []
      }
    ]
  },
  "eo-ai-safety": {
    name: "Executive Order on Safe AI",
    amount: null,
    type: "neutral",
    summary: "Mandates new safety standards for AI systems.",
    affects: "AI developers and federal agencies",
    children: [
      {
        name: "Safety Testing Mandates",
        amount: null,
        type: "new",
        summary: "Requires red-teaming for all foundation models.",
        affects: "AI developers",
        children: []
      },
      {
        name: "Privacy Guardrails",
        amount: null,
        type: "increase",
        summary: "Strengthens privacy protections for training data.",
        affects: "Data brokers and consumers",
        children: []
      }
    ]
  }
};

export const api = {
  getBills: async (): Promise<BillMeta[]> => {
    // Simulate network delay
    await new Promise(r => setTimeout(r, 200));
    return mockBills;
  },
  
  getHierarchy: async (bill_id: string): Promise<Node> => {
    await new Promise(r => setTimeout(r, 200));
    if (!mockHierarchy[bill_id]) throw new Error("Bill not found");
    return mockHierarchy[bill_id];
  },
  
  explain: async (req: ExplainRequest): Promise<ExplainResponse> => {
    // Simulate a longer delay for the LLM
    await new Promise(r => setTimeout(r, 1500));
    return {
      paragraphs: [
        `This section, "${req.node.name}", represents a ${req.node.type} in policy. ${req.node.summary}`,
        `The primary groups impacted are ${req.node.affects.toLowerCase()}. The magnitude of this change is ${req.node.amount !== null ? '$' + (req.node.amount / 1000000).toFixed(1) + 'M' : 'unquantified in direct dollars'}.`,
        `Further details would be generated by the Gemini 2.5 Flash model analyzing the source text in real-time, matching the specific context of the requested node path: ${req.node_path.join(" → ")}.`
      ]
    };
  }
};
